inject(


"/* unused\n"
+"constant('SCRIPTS_INJECTION',\n"
+"	{\n"
+"		'/nonexistingsite_whatever_shared_utils.js'	: 'js/shared/utils.js'\n"
+"		, '/nonexistingsite_whatever_utils.js'		: 'js/injection/utils.js'\n"
+"		, '/nonexistingsite_whatever_parameters.js'	: 'js/injection/parameters.js'\n"
+"		, '/nonexistingsite_whatever_cookie.js'		: 'js/injection/cookie.js'\n"
+"		, '/nonexistingsite_whatever_hook.js'		: 'js/injection/hook.js'\n"
+"		, '/nonexistingsite_whatever_injection.js'	: 'js/injection/main.js'\n"
+"	});*/\n"
+"\n"
+"\n"
+"\n"
+"var PARAM_URL = 'paranoia.chrome/getparams';\n"
+"\n"



+"// for content, background, injection\n"
+"/*unused\n"
+"function constant(strKey, objectValue)\n"
+"{\n"
+"	Object.defineProperty(window, strKey,\n"
+"	{\n"
+"		value: objectValue,\n"
+"		configurable: false,\n"
+"		enumerable: false,\n"
+"		writable: false\n"
+"	});\n"
+"}*/\n"
+"\n"
+"// ts in ms\n"
+"function timestamp()\n"
+"{\n"
+"	return new Date().getTime();\n"
+"}\n"
+"\n"
+"function getDomainPrefix(strMainFrameDomain)\n"
+"{\n"
+"	return 'paranoia'+strMainFrameDomain.replace(/[^a-z0-9]/gi, '');\n"
+"}\n"
+"\n"
+"function getDomain(strURL)\n"
+"{\n"
+"	var match = strURL \n"
+"				? strURL.match(/(?:(?:https?|s?ftps?|chrome|about):\\/\\/)([^\\/\\:]+)/i) // /(?:(?:https?|s?ftps?|chrome|about):\\/\\/)(?:[^\\.]+\\.){0,1}([^\\.\\/\\:]+\\.[^\\/\\.\\:]+)/i) ///(?:(?:https?|s?ftps?|chrome|about):\\/\\/)([^\\/]+)/i)\n"
+"				: null;\n"
+"\n"
+"	var strDomain =  match\n"
+"				? match[1]\n"
+"				: '';\n"
+"\n"
+"	// convert subdomain to tld\n"
+"	strDomain = strDomain.substring(1+strDomain.lastIndexOf('.', strDomain.lastIndexOf('.')-1));\n"
+"	var strGroup = GROUPS[strDomain] ? GROUPS[strDomain] : strDomain;\n"
+"	return strGroup;\n"
+"}\n"
+"\n"



+"\n"
+"\n"
+"function randfloat(min, max)\n"
+"{\n"
+"	return Math.random() * (max-min) +min;\n"
+"}\n"
+"\n"
+"function rand(min, max)\n"
+"{\n"
+"	return parseInt(randfloat(min, max));\n"
+"}\n"
+"\n"
+"function clearStorage(storage, prefix)\n"
+"{\n"
+"	if(storage)\n"
+"	{\n"
+"	//	var keys = storage.keys();\n"
+"\n"
+"		for(var i = 0; i < storage.length; i++)\n"
+"		{\n"
+"			var key = storage.key(i);\n"
+"			if(key && key.indexOf(prefix) == 0)\n"
+"			{\n"
+"				storage.removeItem(key);\n"
+"			}\n"
+"		}\n"
+"	}\n"
+"}\n"
+"\n"
+"\n"
+"function clearCache(storage, prefix)\n"
+"{\n"
+"	if(storage)\n"
+"	{\n"
+"		var keys = storage.keys();\n"
+"		for(var key in keys)\n"
+"		{\n"
+"			if(key && key.indexOf(prefix) == 0)\n"
+"			{\n"
+"				storage.delete(key);\n"
+"			}\n"
+"		}\n"
+"	}\n"
+"}\n"



+"var Parameters = new function()\n"
+"{\n"
+"	var private = {};\n"
+"	var public = {};\n"
+"\n"
+"	private.m_mapParams = {};\n"
+"	private.m_bLoaded = false;\n"
+"	private.m_aCallbacks = [];\n"
+"\n"
+"	public.getPlatfrom = function() {\n"
+"		var strUserAgent = public.getUserAgent();\n"
+"		var strPlatform = '';\n"
+"\n"
+"		if(strUserAgent)\n"
+"		{\n"
+"			if(strUserAgent.toLowerCase().indexOf('linux') >= 0)\n"
+"			{\n"
+"				strPlatform = 'Linux x86_64';\n"
+"			}\n"
+"			else if(strUserAgent.toLowerCase().indexOf('windows') >= 0)\n"
+"			{\n"
+"				strPlatform = 'Win32';\n"
+"			}\n"
+"			else if(strUserAgent.toLowerCase().indexOf('mac') >= 0\n"
+"						&& strUserAgent.toLowerCase().indexOf('intel') >= 0)\n"
+"			{\n"
+"				strPlatform = 'MacIntel';\n"
+"			}\n"
+"			else if(strUserAgent.toLowerCase().indexOf('mac') >= 0\n"
+"						&& strUserAgent.toLowerCase().indexOf('68k') >= 0)\n"
+"			{\n"
+"				strPlatform = 'Mac68K';\n"
+"			}\n"
+"			else if(strUserAgent.toLowerCase().indexOf('mac') >= 0\n"
+"						&& strUserAgent.toLowerCase().indexOf('powerpc') >= 0)\n"
+"			{\n"
+"				strPlatform = 'MacPPC';\n"
+"			}\n"
+"		}\n"
+"		return strPlatform;\n"
+"	};\n"
+"\n"
+"	public.isFirefox = function() {\n"
+"		return public.getUserAgent().toLowerCase().indexOf('firefox') >= 0;\n"
+"	};\n"
+"\n"
+"	public.getAppNameCode = function() {\n"
+"		var strAppName = public.getUserAgent();\n"
+"		return strAppName.length > 0 ? strAppName.substring(0, strAppName.indexOf('/')) : '';\n"
+"	};\n"
+"\n"
+"	public.getAppVersion = function() {\n"
+"		var strAppName = public.getUserAgent();\n"
+"		return strAppName.length > 0 ? strAppName.substring(strAppName.indexOf('/')+1) : '';\n"
+"	};\n"
+"\n"
+"	public.getUserAgent = function() {\n"
+"		return private.m_mapParams['userAgent'] ? private.m_mapParams['userAgent'] : '';\n"
+"	};\n"
+"\n"
+"	public.shouldClear = function() {\n"
+"		return private.m_mapParams['shouldClear'] == 'true';\n"
+"	};\n"
+"	\n"
+"	public.getDomain = function() {\n"
+"		return private.m_mapParams['domain'];\n"
+"	};\n"
+"\n"
+"	public.onLoaded = function(callback) {\n"
+"		if(private.m_bLoaded)\n"
+"		{\n"
+"			callback();\n"
+"		}\n"
+"		else\n"
+"		{\n"
+"			private.m_aCallbacks.push(callback);\n"
+"		}\n"
+"	};\n"
+"\n"
+"	private.updateData = function(strHash) {\n"
+"\n"
+"		if(strHash != null)\n"
+"		{\n"
+"			var astrParams = strHash.split('&');\n"
+"\n"
+"			for(var key in astrParams)\n"
+"			{\n"
+"				var astrKeyValue = astrParams[key].split('=');\n"
+"				private.m_mapParams[astrKeyValue[0]] = decodeURIComponent(astrKeyValue[1]);\n"
+"			}\n"
+"		}\n"
+"	};\n"
+"\n"
+"	private.executePendingCallbacks = function() {\n"
+"		private.m_bLoaded = true;\n"
+"\n"
+"		for(var key in private.m_aCallbacks)\n"
+"		{\n"
+"			private.m_aCallbacks[key]();\n"
+"		}\n"
+"\n"
+"		private.m_aCallbacks = [];\n"
+"	};\n"
+"\n"
+"	private.load = function()\n"
+"	{\n"
+"		try\n"
+"		{\n"
+"			var req = new XMLHttpRequest();\n"
+"			req.open('GET', window.location+PARAM_URL);//+'/nonsense-yay-more-words-okay/getparams');//\n"
+"			\n"
+"			req.onreadystatechange = function() {\n"
+"				if(4 == req.readyState\n"
+"					/*404 will likly be returned.. && 200 == req.status*/)\n"
+"				{console.log('url: '+req.responseURL);\n"
+"					private.updateData(req.responseURL.split('?')[1]);//req.getResponseHeader('paranoia'));\n"
+"					private.executePendingCallbacks();\n"
+"				}\n"
+"			};\n"
+"			req.send();\n"
+"		}\n"
+"		catch(e)\n"
+"		{\n"
+"			// avoid to display 404-error\n"
+"		}\n"
+"	};\n"
+"\n"
+"	public.constructor = function() {\n"
+"		private.load();\n"
+"\n"
+"		public.constructor = undefined;//delete public.constructor;\n"
+"		return public;\n"
+"	};\n"
+"\n"
+"	return public.constructor();\n"
+"}();\n"



+"var CookieManager = function()\n"
+"{\n"
+"	var private = {};\n"
+"	var public = {};\n"
+"\n"
+"	private.getDomain = function()\n"
+"	{\n"
+"		return Parameters.getDomain();\n"
+"	};\n"
+"	private.getDomainPrefix = function()\n"
+"	{\n"
+"		return getDomainPrefix(private.getDomain());\n"
+"	};\n"
+"	private.getRegexDomainPrefix = function()\n"
+"	{\n"
+"		return new RegExp(private.getDomainPrefix(), 'g');\n"
+"	};\n"
+"\n"
+"\n"
+"	public.constructor = function(objectDocument, getterCookieDocument)\n"
+"	{\n"
+"		Object.defineProperty(objectDocument, 'cookie', {\n"
+"							get: function()\n"
+"							{\n"
+"								var strRet = '';\n"
+"								var astrTmpCookies = getterCookieDocument().cookie.split(';');\n"
+"\n"
+"								for(var i = 0, nLen = astrTmpCookies.length\n"
+"									; i < nLen\n"
+"										&& private.getDomain() // return no data if we haven't received the data\n"
+"									; i++)\n"
+"								{\n"
+"									var astrData = astrTmpCookies[i].split('=');\n"
+"									if(astrData[0].trim().indexOf(private.getDomainPrefix()) == 0)\n"
+"									{\n"
+"										if(strRet.length != 0)\n"
+"										{\n"
+"											strRet += ';';\n"
+"										}\n"
+"\n"
+"										strRet += astrTmpCookies[i];\n"
+"									}\n"
+"								}\n"
+"\n"
+"								if(private.getDomain())\n"
+"								{\n"
+"									strRet = strRet.replace(private.getRegexDomainPrefix(), '');\n"
+"								}\n"
+"\n"
+"								return strRet;\n"
+"							},\n"
+"							configurable: false,\n"
+"							enumerable: false,\n"
+"							set: function(strCookies)\n"
+"							{\n"
+"								if(strCookies\n"
+"									&& private.getDomain())\n"
+"								{\n"
+"									var astrCookies = strCookies.split(';');\n"
+"\n"
+"									for(var i = 0, nLen = astrCookies.length\n"
+"										; i < nLen\n"
+"										; i++)\n"
+"									{\n"
+"										var strCookie = astrCookies[i].trim();\n"
+"										var nPos = strCookie.indexOf('=');\n"
+"										if(nPos >= 0)\n"
+"										{\n"
+"											strCookie = \n"
+"												// before first '='\n"
+"												private.getDomainPrefix()\n"
+"												+strCookie.substring(0, nPos).replace(/[ \\t]*/g, '')\n"
+"												// after first '='\n"
+"												+strCookie.substring(nPos);\n"
+"										}\n"
+"										else\n"
+"										{\n"
+"											strCookie = private.getDomainPrefix() + strCookie;\n"
+"										}\n"
+"\n"
+"										getterCookieDocument().cookie = strCookie;\n"
+"									}\n"
+"								}\n"
+"							}\n"
+"						});\n"
+"	};\n"
+"\n"
+"	return public.constructor.apply(public, arguments);\n"
+"};\n"



+"\n"
+"// this class should be able to create single level hooks\n"
+"// -> hooking a hook function shouldn't be possible!\n"
+"var Hook = new function()\n"
+"{\n"
+"	var private = {};\n"
+"	var public = {};\n"
+"\n"
+"	// methods which are passed to a callback function to create hooks\n"
+"	// -> createHookFunction should only be called from a callback (to ensure the correct usage of this class)\n"
+"	// 	  otherwise the hooks wouldn't be added to e.g. iframes\n"
+"	var special_accessable = {};\n"
+"\n"
+"	private.m_aOurHooks = [];\n"
+"\n"
+"\n"
+"	// methods / functions which adds our hooks to the objects\n"
+"	private.m_aOurHookCreatorsDocument = [];\n"
+"	private.m_aOurHookCreatorsWindow = [];\n"
+"\n"
+"	private.m_protoIFrame = null;\n"
+"\n"
+"	private.m_cookieIFrame = null;\n"
+"	private.m_cookieDocument = null;/*contains the unmodified cookie object, everything else will be modified*/\n"
+"\n"
+"	private.m_objectStorage = null; // used to restore the storage prototype\n"
+"\n"
+"	private.getCookieDocument = function()\n"
+"	{\n"
+"		return private.m_cookieDocument;\n"
+"	};\n"
+"	private.getStorage = function()\n"
+"	{\n"
+"		return private.m_objectStorage;\n"
+"	};\n"
+"	private.init = function()\n"
+"	{\n"
+"		public.setupHookDocument(function(createHookFunction, documentObject)\n"
+"		{\n"
+"			if(private.m_cookieDocument != documentObject\n"
+"				&& !Object.getOwnPropertyDescriptor(documentObject, 'cookie'))\n"
+"			{\n"
+"				new CookieManager(documentObject, private.getCookieDocument);\n"
+"			}\n"
+"		});\n"
+"		public.setupHookWindow(function(createHookFunction, windowObject)\n"
+"		{\n"
+"			if(windowObject.DOMImplementation)\n"
+"			{\n"
+"				windowObject.DOMImplementation.prototype.createHTMLDocument = createHookFunction(windowObject.DOMImplementation.prototype.createHTMLDocument, private.createHookHTMLDocumentConstructor);\n"
+"			}\n"
+"			else\n"
+"			{\n"
+"				windowObject.DOMImplementation = window.DOMImplementation;\n"
+"			}\n"
+"\n"
+"			// we have to 'disable' these variables for security reasons\n"
+"			try\n"
+"			{\n"
+"				Object.defineProperty(windowObject.HTMLIFrameElement.prototype, 'contentDocument', {\n"
+"									get: function()\n"
+"									{\n"
+"										var ret = null;\n"
+"										var bIsCookieIFrame = this == private.m_cookieIFrame;\n"
+"										var bIsCookieDocumentInited = private.m_cookieDocument != null;\n"
+"\n"
+"										private.makeIFrameAccessable(this,\n"
+"											// skip hooking methods if iframe == our cookie iframe and we still need to grap the document\n"
+"											bIsCookieIFrame && !bIsCookieDocumentInited);\n"
+"										ret = this.contentDocument;\n"
+"										private.revokeIFrameAccess(this);\n"
+"\n"
+"										if(bIsCookieIFrame && bIsCookieDocumentInited)\n"
+"										{\n"
+"											// lol no you're not allowed to read all cookies\n"
+"											ret = document;\n"
+"										}\n"
+"\n"
+"\n"
+"										return ret;\n"
+"									},\n"
+"									configurable: false,\n"
+"									enumerable: false,\n"
+"									set: function(){}\n"
+"								});\n"
+"			}\n"
+"			catch(e){}\n"
+"			try\n"
+"			{\n"
+"				Object.defineProperty(windowObject.HTMLIFrameElement.prototype, 'contentWindow', {\n"
+"									get: function()\n"
+"									{\n"
+"										var ret = null;\n"
+"										var bIsCookieIFrame = this == private.m_cookieIFrame;\n"
+"										var bIsCookieDocumentInited = private.m_cookieDocument != null;\n"
+"										\n"
+"										private.makeIFrameAccessable(this);\n"
+"										ret = this.contentWindow;\n"
+"										private.revokeIFrameAccess(this);\n"
+"\n"
+"										if(bIsCookieIFrame && bIsCookieDocumentInited)\n"
+"										{\n"
+"											// lol no you're not allowed to read all cookies\n"
+"											ret = window;\n"
+"										}\n"
+"\n"
+"\n"
+"										return ret;\n"
+"									},\n"
+"									configurable: false,\n"
+"									enumerable: false,\n"
+"									set: function(){}\n"
+"								});\n"
+"			}\n"
+"			catch(e){}\n"
+"		});\n"
+"	};\n"
+"\n"
+"	private.createHookHTMLDocumentConstructor =function(create)\n"
+"	{\n"
+"		return function() {\n"
+"			var ret = create ? create.apply(this, arguments) : null;\n"
+"\n"
+"			private.addDocumentHooks(ret);\n"
+"\n"
+"			return ret;\n"
+"		};\n"
+"	};\n"
+"	private.createHookGetComputedStyle =function(create)\n"
+"	{\n"
+"		var newObj = null;\n"
+"\n"
+"		return function() {\n"
+"			var ret = create ? create.apply(this, arguments) : null;\n"
+"\n"
+"			// protect against data revealing via css\n"
+"			// e.g. visited sites via ':visited' selector\n"
+"			if(newObj == null)\n"
+"			{\n"
+"				for(var key in ret)\n"
+"				{\n"
+"					if(typeof key == 'string')\n"
+"					{\n"
+"						var objNewVal = null;\n"
+"\n"
+"						switch(typeof ret[key])\n"
+"						{\n"
+"							case 'string':\n"
+"								objNewVal = '';\n"
+"								break;\n"
+"							case 'number':\n"
+"								objNewVal = 0;\n"
+"								break;\n"
+"							case 'boolean':\n"
+"								objNewVal = false;\n"
+"								break;\n"
+"							case 'function':\n"
+"								objNewVal = function(){return '0';};\n"
+"								break;\n"
+"						}\n"
+"					}\n"
+"\n"
+"					try\n"
+"					{\n"
+"						Object.defineProperty(ret, key, {\n"
+"							value: objNewVal,\n"
+"							configurable: false,\n"
+"							enumerable: false,\n"
+"							writable: false\n"
+"						});\n"
+"					}\n"
+"					catch(e){}\n"
+"				}\n"
+"\n"
+"				newObj = ret;\n"
+"			}\n"
+"\n"
+"			return newObj;\n"
+"		};\n"
+"	};\n"
+"\n"
+"	private.addDocumentHooks = function(documentObject)\n"
+"	{\n"
+"		for (var i in private.m_aOurHookCreatorsDocument)\n"
+"		{\n"
+"			private.m_aOurHookCreatorsDocument[i](special_accessable.createHookFunction, documentObject);\n"
+"		}\n"
+"	};\n"
+"	// legacy as we decided to give every iframe the same document and window object.. as we know no way to instantly hook every new iframe (innerHTML is a big problem..)// ensure our hooks are present on every document / window object\n"
+"	private.addMethodsIfNecessary = function(node)\n"
+"	{\n"
+"		if(node)\n"
+"		{\n"
+"			try\n"
+"			{\n"
+"				if(node.contentDocument)\n"
+"				{\n"
+"					private.addDocumentHooks(node.contentDocument);\n"
+"				}\n"
+"			}\n"
+"			catch(e)\n"
+"			{\n"
+"			}\n"
+"			try\n"
+"			{\n"
+"				if(node.contentWindow)\n"
+"				{\n"
+"					for (var i in private.m_aOurHookCreatorsWindow)\n"
+"					{\n"
+"						private.m_aOurHookCreatorsWindow[i](special_accessable.createHookFunction, node.contentWindow);\n"
+"					}\n"
+"\n"
+"				}\n"
+"			}\n"
+"			catch(e)\n"
+"			{\n"
+"			}\n"
+"		}\n"
+"	};\n"
+"\n"
+"\n"
+"	private.registerHookFunction = function(func)\n"
+"	{\n"
+"		private.m_aOurHooks.push(func);\n"
+"	};\n"
+"\n"
+"	public.isHookFunction = function(func)\n"
+"	{\n"
+"		return private.m_aOurHooks.indexOf(func) >= 0;\n"
+"	};\n"
+"\n"
+"	special_accessable.createHookFunction = function(funcTarget, funcCreateHookFunc)\n"
+"	{\n"
+"		var hook = funcTarget;\n"
+"\n"
+"		// we don't want to hook hook-functions\n"
+"		if(funcTarget && !public.isHookFunction(hook) && typeof funcCreateHookFunc == 'function')\n"
+"		{\n"
+"			hook = funcCreateHookFunc(funcTarget);\n"
+"			private.registerHookFunction(hook);\n"
+"		}\n"
+"\n"
+"		return hook;\n"
+"	};\n"
+"\n"
+"	/**\n"
+"	* callback		A function which adds the hooks to the functions\n"
+"	*				Two arguments will be passed to the callback\n"
+"	*				-> function(createHookFunction, documentObject)\n"
+"	*				{\n"
+"	*					documentObject.theMethodIwantToBeHooked = createHookFunction(documentObject.theMethodIwantToBeHooked\n"
+"	*																				, theMethodWhichCreatesTheHookMethod);\n"
+"	*				}\n"
+"	*/\n"
+"	public.setupHookDocument = function(callback)\n"
+"	{\n"
+"		private.m_aOurHookCreatorsDocument.push(callback);\n"
+"\n"
+"		// hook methods for current frame / site\n"
+"		callback(special_accessable.createHookFunction, document);\n"
+"	};\n"
+"\n"
+"	public.setupHookWindow = function(callback)\n"
+"	{\n"
+"		private.m_aOurHookCreatorsWindow.push(callback);\n"
+"\n"
+"		// hook methods for current frame / site\n"
+"		callback(special_accessable.createHookFunction, window);\n"
+"	};\n"
+"\n"
+"	private.setupIFrames = function()\n"
+"	{\n"
+"		var iframe = document.createElement('iframe');\n"
+"		iframe.sandbox = 'allow-same-origin';\n"
+"		document.documentElement.insertBefore(iframe, document.documentElement.firstChild);\n"
+"		private.m_protoIFrame = iframe.contentWindow.HTMLIFrameElement.prototype;\n"
+"		document.documentElement.removeChild(iframe);\n"
+"\n"
+"		return iframe;\n"
+"	};\n"
+"\n"
+"	private.setupIFrameCookie = function()\n"
+"	{\n"
+"		var iframe = document.createElement('iframe');\n"
+"		iframe.sandbox = 'allow-same-origin';\n"
+"		iframe.setAttribute('style', 'height:1px;width:1px;opacity:0;pointer-events: none;position: absolute;');\n"
+"		document.documentElement.insertBefore(iframe, document.documentElement.firstChild);\n"
+"		private.m_cookieIFrame = iframe;\n"
+"		private.m_cookieDocument = iframe.contentDocument;\n"
+"		private.m_objectStorage = iframe.localStorage\n"
+"								? iframe.localStorage\n"
+"								: iframe.sessionStorage\n"
+"								? iframe.sessionStorage\n"
+"								: iframe.globalStorage\n"
+"								? iframe.globalStorage\n"
+"								: null;\n"
+"		//document.documentElement.removeChild(iframe);\n"
+"	};\n"
+"\n"
+"	/**\n"
+"	* If this method returns true you have to ensure\n"
+"	* that {@link private.revokeIFrameAccess} is called.\n"
+"	* We need to do this to avoid to allow our enemies to fetch the prototype.\n"
+"	*/\n"
+"	private.makeIFrameAccessable = function(node, bSkipAddMet)\n"
+"	{\n"
+"		var bRet = false;\n"
+"\n"
+"		node.__proto__ = private.m_protoIFrame;\n"
+"		if(!bSkipAddMet)\n"
+"		{\n"
+"			private.addMethodsIfNecessary(node);\n"
+"\n"
+"			if(node.src\n"
+"				&& (node.src.indexOf('http://') == 0\n"
+"					|| node.src.indexOf('https://') == 0))\n"
+"			{\n"
+"				bRet = true;\n"
+"			}\n"
+"		}\n"
+"\n"
+"		return bRet;\n"
+"	};\n"
+"\n"
+"	private.revokeIFrameAccess = function(node)\n"
+"	{\n"
+"		node.__proto__ = window.HTMLIFrameElement.prototype;\n"
+"		//alert('ok: '+(node.__proto__ == window.HTMLIFrameElement.prototype));\n"
+"	};\n"
+"\n"
+"	private.eventListenerIFrame = function(e)\n"
+"	{\n"
+"		if(e && e.path && e.path.length > 0 && e.path[0])\n"
+"		{\n"
+"			if(e.path[0].src.indexOf(':blank') >= 0)\n"
+"			{\n"
+"				private.addMethodsIfNecessary(e.path[0]);\n"
+"			}\n"
+"			//private.makeIFrameAccessable(e.path[0]);\n"
+"		}\n"
+"	};\n"
+"\n"
+"	public.constructor = function()\n"
+"	{\n"
+"		private.setupIFrames();\n"
+"		private.init();\n"
+"		private.setupIFrameCookie();\n"
+"\n"
+"		public.constructor = undefined;//delete public.constructor;\n"
+"		return public;\n"
+"	};\n"
+"\n"
+"	return public.constructor();\n"
+"}();\n"
+"\n"



+"\n"
+"var globStor = window.globalStorage;\n"
+"var locStor = window.localStorage;\n"
+"var sessStor = window.sessionStorage;\n"
+"\n"
+"function createFakeStorage(strStorageName) {\n"
+"	if(window[strStorageName])\n"
+"	{\n"
+"		Object.defineProperty(window, strStorageName, {\n"
+"			value: {length: 0,key:function(){return null},getItem:function(){return null},setItem:function(){},removeItem:function(){},clear:function(){}},\n"
+"			configurable: true,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"}\n"
+"function restoreStorage(strStorageName, objectBackup) {\n"
+"	if(window[strStorageName]\n"
+"		&& objectBackup)\n"
+"	{\n"
+"		Object.defineProperty(window, strStorageName, {\n"
+"			value: objectBackup,\n"
+"			configurable: true,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"}\n"
+"createFakeStorage('globalStorage');\n"
+"createFakeStorage('localStorage');\n"
+"createFakeStorage('sessionStorage');\n"
+"Parameters.onLoaded(function()\n"
+"{\n"
+"	if(Parameters.shouldClear())\n"
+"	{\n"
+"		// todo add these storages to our sandbox\n"
+"		clearStorage(globStor, getDomainPrefix(Parameters.getDomain()));\n"
+"		clearStorage(locStor, getDomainPrefix(Parameters.getDomain()));\n"
+"		clearStorage(sessStor, getDomainPrefix(Parameters.getDomain()));\n"
+"	//	clearCache(window.caches, getDomainPrefix(Parameters.getDomain()));\n"
+"\n"
+"		// reset window.name\n"
+"		window.name = '';\n"
+"	}\n"
+"\n"
+"	restoreStorage('globalStorage', globStor);\n"
+"	restoreStorage('localStorage', locStor);\n"
+"	restoreStorage('sessionStorage', sessStor);\n"
+"\n"
+"/*\n"
+"	Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"	{\n"
+"		Object.defineProperty(windowObject.localStorage.prototype, '', {\n"
+"			value: {length: 0,key:function(){return null},getItem:function(){return null},setItem:function(){},removeItem:function(){},clear:function(){}},\n"
+"			configurable: true,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	});*/\n"
+"});\n"
+"\n"
+"\n"
+"var drawRandomThings = function(ctx, width, height)\n"
+"{\n"
+"	var nSidePadding = width > 0 ? 1 : 0;\n"
+"	var nBottomPadding = height > 0 ? 1 : 0;\n"
+"\n"
+"	/*\n"
+"	* Um kaum bemerkbare Punkte hinzuschmieren\n"
+"	*/\n"
+"	var nLeft = rand(0, width - nSidePadding);\n"
+"	var nWidth = 1;\n"
+"	var nTop = rand(0, height - nBottomPadding);\n"
+"	var nHeight = 1;\n"
+"\n"
+"	var nRed = rand(0, 255);\n"
+"	var nGreen = rand(0, 255);\n"
+"	var nBlue = rand(0, 255);\n"
+"	var fAlpha = randfloat(0.01, .2);\n"
+"	var strRandColor = 'rgba('+nRed+', '+nGreen+', '+nBlue+', '+fAlpha+')';\n"
+"\n"
+"\n"
+"	ctx.fillStyle = strRandColor;\n"
+"	ctx.fillRect(nLeft, nTop, nWidth, nHeight);\n"
+"};\n"
+"\n"
+"var createHookGetContext =function(real_function)\n"
+"{\n"
+"	return function()\n"
+"	{\n"
+"		var ret = real_function.apply(this, arguments);\n"
+"\n"
+"		var nMaxLoops = (this.width * this.height)/500;\n"
+"		var nLoops = rand(1, Math.max(1, nMaxLoops));\n"
+"		for(var i = 0; i < nLoops; i++)\n"
+"		{\n"
+"			drawRandomThings(ret, this.width, this.height);\n"
+"		}\n"
+"\n"
+"		return ret;\n"
+"	};\n"
+"};\n"
+"var createHookToDataURL =function(real_function)\n"
+"{\n"
+"	return function()\n"
+"	{\n"
+"		this.getContext('2d');\n"
+"\n"
+"		return real_function.apply(this, arguments);\n"
+"	};\n"
+"};\n"
+"\n"
+"\n"
+"// protection against canvas fingerprinting\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	if(windowObject.HTMLCanvasElement)\n"
+"	{\n"
+"		windowObject.HTMLCanvasElement.prototype.getContext = createHookFunction(windowObject.HTMLCanvasElement.prototype.getContext, createHookGetContext);\n"
+"		windowObject.HTMLCanvasElement.prototype.toDataURL = createHookFunction(windowObject.HTMLCanvasElement.prototype.toDataURL, createHookToDataURL);\n"
+"	}\n"
+"	else\n"
+"	{\n"
+"		windowObject.HTMLCanvasElement = window.HTMLCanvasElement;\n"
+"	}\n"
+"});\n"
+"\n"
+"// hide browser plugins\n"
+"Hook.setupHookDocument(function(createHookFunction, documentObject)\n"
+"{\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(documentObject, 'plugins', {\n"
+"			value: [],\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"});\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'plugins', {\n"
+"			value: {length:0,item:function(){return null;},namedItem:function(){return null;},refresh:function(){}},\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'mimeTypes', {\n"
+"			value: [],\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"});\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"// according to http://ip-check.info/ we should swap window.name with a constant\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	/* this breaks many sites... like disqus....\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject, 'name', {\n"
+"							get: function()\n"
+"							{\n"
+"								var strRet = '';\n"
+"\n"
+"								if(this.strTmpName)\n"
+"								{\n"
+"									strRet = this.strTmpName;\n"
+"								}\n"
+"\n"
+"								return strRet;\n"
+"							},\n"
+"							configurable: false,\n"
+"							enumerable: false,\n"
+"							set: function(strNew)\n"
+"							{\n"
+"								this.strTmpName = strNew;\n"
+"							}\n"
+"						});\n"
+"	}\n"
+"	catch(e){}*/\n"
+"});\n"
+"// make font detection more difficult - it's still possible...\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.CSSStyleDeclaration.prototype, 'fontFamily', {\n"
+"							get: function(){return '';},\n"
+"							configurable: false,\n"
+"							enumerable: false,\n"
+"							set: function(){}\n"
+"						});\n"
+"	}\n"
+"	catch(e){}\n"
+"});\n"
+"\n"
+"// change the browser language to english - most common browser language\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'language', {\n"
+"			value: 'en',\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'languages', {\n"
+"			value: undefined,\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"});\n"
+"\n"
+"// hide the tab history\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.history, 'length', {\n"
+"			value: 0,//{back:function(){},go:function(){},forward:function(){},replaceState:function(){},state:0,pushState:function(){}, length:0},\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"});\n"
+"\n"
+"// block attacks like determine the browser history though ':visited' css\n"
+"// this may break a page..\n"
+"//e.g. phpMyAdmin......\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	//windowObject.getComputedStyle = createHookFunction(windowObject.getComputedStyle, private.createHookGetComputedStyle);\n"
+"});\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"// block webrtc\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	// webrtc block\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject, 'RTCPeerConnection', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"\n"
+"		Object.defineProperty(windowObject, 'webkitRTCPeerConnection', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"\n"
+"		Object.defineProperty(windowObject.navigator, 'getUserMedia', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"\n"
+"		Object.defineProperty(windowObject.navigator, 'webkitGetUserMedia', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"\n"
+"		Object.defineProperty(windowObject, 'RTCSessionDescription', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"\n"
+"		Object.defineProperty(windowObject, 'webkitRTCSessionDescription', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"\n"
+"		Object.defineProperty(windowObject, 'MediaStreamTrack', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject, 'webkitMediaStreamTrack', {\n"
+"				value: undefined,\n"
+"				configurable: false,\n"
+"				enumerable: false,\n"
+"				writable: false\n"
+"			});\n"
+"	}\n"
+"	catch(e){}\n"
+"	// ende webrtc\n"
+"});\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"// hide some informations in the navigator object\n"
+"Hook.setupHookWindow(function(createHookFunction, windowObject)\n"
+"{\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'maxTouchPoints', {\n"
+"			value: 0,\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'hardwareConcurrency', {\n"
+"			value: undefined,\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'oscpu', {\n"
+"			value: undefined,\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'platform', {\n"
+"			get: function(){return Parameters.getPlatfrom();},\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			set: function(){}\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'userAgent', {\n"
+"			get: function(){return Parameters.getUserAgent();},\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			set: function(){}\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"\n"
+"\n"
+"	// todo improve the sentences (bad english)\n"
+"	// !!!!!! important this needs to be at the bottom\n"
+"	// as it changes the name of variables\n"
+"	// -> could break e.g. the webrtc block if it's on the top of the code\n"
+"	// replace the webkit prefix for firefox user agents\n"
+"	(function(windowObject)\n"
+"	{\n"
+"		Parameters.onLoaded(function(){\n"
+"\n"
+"			if(Parameters.isFirefox())\n"
+"			{\n"
+"				for(var key in windowObject)\n"
+"				{\n"
+"					if(key != null\n"
+"						&& key.indexOf('webkit') == 0)\n"
+"					{\n"
+"						var keyNew = key.replace('webkit', 'moz');\n"
+"						var strSource = null;\n"
+"\n"
+"						try\n"
+"						{\n"
+"							strSource = windowObject[key].toString().replace('webkit', 'moz');\n"
+"						} catch(e) {}\n"
+"\n"
+"						(function(windowObject, keyNew, key, strSource)\n"
+"						{\n"
+"							try\n"
+"							{\n"
+"								Object.defineProperty(windowObject, keyNew, {\n"
+"									value: windowObject[key],\n"
+"									configurable: true,\n"
+"									enumerable: true,\n"
+"									writable: false\n"
+"								});\n"
+"								windowObject[keyNew].toString = function(){return strSource;};\n"
+"\n"
+"								// remove old key from window-object\n"
+"								Object.defineProperty(windowObject, key, {\n"
+"									value: undefined,\n"
+"									configurable: true,\n"
+"									enumerable: false,\n"
+"									writable: true\n"
+"								});\n"
+"							}\n"
+"							catch(e){}\n"
+"						})(windowObject, keyNew, key, strSource);\n"
+"					}\n"
+"				}\n"
+"			}\n"
+"		});\n"
+"	})(windowObject);\n"
+"\n"
+"\n"
+"\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'appVersion', {\n"
+"			get: function(){return Parameters.getAppVersion();},\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			set: function(){}\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'appName', {\n"
+"			value: 'Netscape', // value doesn't differ in firefox & chrome\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'appCodeName', {\n"
+"			value: 'Mozilla', // value doesn't differ in firefox & chrome\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'vendor', {\n"
+"			value: '',\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"	try\n"
+"	{\n"
+"		Object.defineProperty(windowObject.navigator, 'vendorSub', {\n"
+"			value: '',\n"
+"			configurable: false,\n"
+"			enumerable: false,\n"
+"			writable: false\n"
+"		});\n"
+"	}\n"
+"	catch(e){}\n"
+"});\n"
+"//alert('so');\n"
+"// execute the blocked inline-scripts\n"
+"// this breaks some sites -.-\n"
+"/*setTimeout(function()\n"
+"{\n"
+"	console.clear();\n"
+"var aScripts = document.getElementsByTagName('script');\n"
+"for(var key in aScripts)\n"
+"{\n"
+"	if(aScripts[key]\n"
+"		&& aScripts[key].innerHTML\n"
+"		&& aScripts[key].innerHTML.length > 0)\n"
+"	{\n"
+"		//console.log(aScripts[key].innerHTML);\n"
+"		var strCode = aScripts[key].innerHTML;\n"
+"		eval(strCode);\n"
+"		//var par = aScripts[key].parentElement;\n"
+"		//par.appendChild(par.removeChild(aScripts[key]));\n"
+"	}\n"
+"}\n"
+"}, 0);*/\n"
+"\n"
);